"""Markdown rendering for the generated case set and for regression output."""

from __future__ import annotations

from typing import Any

from .runner import RunMetrics, Violation
from .select import SelectionResult


def _cell(value: Any, limit: int = 60) -> str:
    """Make a value safe to drop into a Markdown table cell."""
    text = str(value).replace("|", "\\|").replace("\n", " ").strip()
    if len(text) > limit:
        text = text[: limit - 1] + "…"
    return text or "—"


def _number(value: Any, digits: int = 4) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        if value == 0:
            return "0"
        if abs(value) < 0.001:
            return f"{value:.8f}".rstrip("0")
        return f"{value:.{digits}f}"
    return str(value)


def build_report(result: SelectionResult, source_name: str) -> str:
    """Human-readable account of what was selected and, more importantly, why."""
    stats = result.stats()
    context = result.context
    lines: list[str] = []

    lines.append("# trace2eval build report")
    lines.append("")
    lines.append(f"Source log: `{source_name}`")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Traces read | {stats['total_traces']} |")
    lines.append(f"| Distinct questions | {stats['distinct_questions']} |")
    lines.append(f"| Questions with no signal | {stats['questions_without_signals']} |")
    lines.append(f"| Cases generated | {stats['cases']} |")
    lines.append(f"| Log lines collapsed into a case | {stats['dropped_as_duplicate']} |")
    lines.append(f"| Questions below the minimum score | {stats['dropped_below_min_score']} |")
    lines.append(f"| Questions beyond the case limit | {stats['dropped_beyond_limit']} |")
    lines.append("")

    lines.append("## Log-wide baselines")
    lines.append("")
    lines.append("| Statistic | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| p95 latency | {_number(context.p95_latency_ms, 2)} ms |")
    lines.append(f"| p95 cost | ${_number(context.p95_cost_usd, 8)} |")
    lines.append(f"| Median output length | {_number(context.median_output_chars, 1)} chars |")
    lines.append("")

    failures = sum(1 for case in result.cases if not case["reference_is_trusted"])
    lines.append("## Case mix")
    lines.append("")
    lines.append(
        f"- **{failures}** regression seeds (the reference output is the output that "
        f"went wrong — the case exists so it never ships twice)"
    )
    lines.append(
        f"- **{len(result.cases) - failures}** quality anchors (clean trace, so an "
        f"expected shape was inferred from it)"
    )
    lines.append("")

    lines.append("## Cases")
    lines.append("")
    lines.append("| Case | Score | In log | Trusted | Signals | Input |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for case in result.cases:
        signal_names = ", ".join(signal["name"] for signal in case["signals"])
        lines.append(
            "| {id} | {score} | {occurs} | {trusted} | {signals} | {input} |".format(
                id=_cell(case["id"], 12),
                score=_cell(case["score"], 8),
                occurs=_cell(case["occurrences_in_log"], 8),
                trusted="yes" if case["reference_is_trusted"] else "no",
                signals=_cell(signal_names, 48),
                input=_cell(case["input"], 48),
            )
        )
    lines.append("")

    if result.cases:
        lines.append("## Why the top case was chosen")
        lines.append("")
        top = result.cases[0]
        lines.append(f"`{top['id']}` scored **{top['score']}**.")
        lines.append("")
        for signal in top["signals"]:
            lines.append(f"- `{signal['name']}` (+{signal['weight']}) — {signal['detail']}")
        lines.append("")
        for note in top["notes"]:
            lines.append(f"> {note}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Generated by [trace2eval](https://github.com/rfioly/trace2eval). "
        "Review this file before committing the case set — the selection is a "
        "proposal, not a verdict."
    )
    lines.append("")
    return "\n".join(lines)


def render_metrics(metrics: RunMetrics) -> str:
    lines: list[str] = []
    lines.append("| Metric | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Cases | {metrics.total} |")
    lines.append(f"| Passed | {metrics.passed} |")
    lines.append(f"| Failed | {metrics.failed} |")
    if metrics.missing:
        lines.append(f"| Missing outputs | {metrics.missing} |")
    lines.append(f"| Pass rate | {metrics.pass_rate:.2%} |")
    lines.append(f"| Fallback rate | {metrics.fallback_rate:.2%} |")
    if metrics.format_compliance_rate is not None:
        lines.append(f"| Format compliance | {metrics.format_compliance_rate:.2%} |")
    lines.append(f"| Avg latency | {_number(metrics.avg_latency_ms, 2)} ms |")
    lines.append(f"| p95 latency | {_number(metrics.p95_latency_ms, 2)} ms |")
    lines.append(f"| Avg cost | ${_number(metrics.avg_cost_usd, 8)} |")
    return "\n".join(lines)


def render_violations(violations: list[Violation]) -> str:
    if not violations:
        return "No regressions detected."
    lines: list[str] = []
    lines.append("| Metric | Baseline | Current | Rule |")
    lines.append("| --- | --- | --- | --- |")
    for violation in violations:
        lines.append(
            "| {metric} | {baseline} | {current} | {rule} |".format(
                metric=_cell(violation.metric, 24),
                baseline=_cell(_number(violation.baseline), 16),
                current=_cell(_number(violation.current), 16),
                rule=_cell(violation.rule, 40),
            )
        )
    return "\n".join(lines)
